const user = {};
const token = "";
const marketType = [
  //INITIATED 草稿, ACTIVATING 券正在生成, ACTIVATED 券已生成, REJECTED 审批拒绝, ARCHIVED 已删除, TERMINATED 已终止;
  { INITIATED: "草稿" },
  { ACTIVATING: "正在发布" },
  { ACTIVATED: "已发布" },
  { TERMINATED: "已撤销" },
];
const couponType = [
  { NEW: "新券" }, // 可发布
  { PENDING: "未生效" }, // 未生效
  { ACTIVE: "可用" }, //  可用
  { REDEEMED: "已兑换" }, // 已兑换
  { EXPIRED: "已过期" }, // 已过期
];


const listType = [
  { INITIATED: "草稿" },
  { SUBMITTED: "审核中" },
  { PROCESSED: "审核通过" },
  { FAILED: "失败" },
];

//结算的类型
//NONE, MONTHLY, QUARTERLY, ;
//按月结算，按季度结算，按年结算，按活动结算
const listAddType = [
  {
    value: "NONE",
    name: "按活动结算",
  },
  {
    value: "MONTHLY",
    name: "按月结算",
  },
  {
    value: "QUARTERLY",
    name: "按季度结算",
  },
  {
    value: "ANNUAL",
    name: "按年结算",
  },
];


var Operation = {
  MANAGE_ORGANIZATION: "MANAGE_ORGANIZATION",
  LIST_SUBSIDIARIES: "LIST_SUBSIDIARIES",
  VIEW_ORGANIZATION: "VIEW_ORGANIZATION",
  CREATE_SUBSIDIARY: "CREATE_SUBSIDIARY",
  UPDATE_ORGANIZATION: "UPDATE_ORGANIZATION",
  DELETE_SUBSIDIARY: "DELETE_SUBSIDIARY",
  MANAGE_SHIPPING_ADDRESS: "MANAGE_SHIPPING_ADDRESS",
  MANAGE_EMPLOYEE: "MANAGE_EMPLOYEE",
  LIST_EMPLOYEES: "LIST_EMPLOYEES",
  VIEW_EMPLOYEE: "VIEW_EMPLOYEE",
  CREATE_EMPLOYEE: "CREATE_EMPLOYEE",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  ONBOARDING: "ONBOARDING",
  MANAGE_GROUP: "MANAGE_GROUP",
  LIST_GROUPS: "LIST_GROUPS",
  CREATE_GROUP: "CREATE_GROUP",
  VIEW_GROUP: "VIEW_GROUP",
  UPDATE_GROUP: "UPDATE_GROUP",
  DELETE_GROUP: "DELETE_GROUP",
  MANAGE_DISTRIBUTION_POINT: "MANAGE_DISTRIBUTION_POINT",
  LIST_DISTRIBUTION_POINTS: "LIST_DISTRIBUTION_POINTS",
  CREATE_DISTRIBUTION_POINT: "CREATE_DISTRIBUTION_POINT",
  VIEW_DISTRIBUTION_POINT: "VIEW_DISTRIBUTION_POINT",
  UPDATE_DISTRIBUTION_POINT: "UPDATE_DISTRIBUTION_POINT",
  DELETE_DISTRIBUTION_POINT: "DELETE_DISTRIBUTION_POINT",
  JOIN_DISTRIBUTION_NETWORK: "JOIN_DISTRIBUTION_NETWORK",
  MANAGE_CAMPAIGN: "MANAGE_CAMPAIGN",
  LIST_CAMPAIGNS: "LIST_CAMPAIGNS",
  VIEW_CAMPAIGN: "VIEW_CAMPAIGN",
  CREATE_CAMPAIGN: "CREATE_CAMPAIGN",
  UPDATE_CAMPAIGN: "UPDATE_CAMPAIGN",
  DELETE_CAMPAIGN: "DELETE_CAMPAIGN",
  MANAGE_CUSTOMER: "MANAGE_CUSTOMER",
  LIST_CUSTOMERS: "LIST_CUSTOMERS",
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  DELETE_CUSTOMER: "DELETE_CUSTOMER",
  TRANSFER_CUSTOMER: "TRANSFER_CUSTOMER",
  MANAGE_RESOURCE: "MANAGE_RESOURCE",
  MANAGE_PRODUCT: "MANAGE_PRODUCT",
  LIST_PRODUCTS: "LIST_PRODUCTS",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  MANAGE_DEMAND: "MANAGE_DEMAND",
  LIST_DEMANDS: "LIST_DEMANDS",
  VIEW_DEMAND: "VIEW_DEMAND",
  CREATE_DEMAND: "CREATE_DEMAND",
  UPDATE_DEMAND: "UPDATE_DEMAND",
  DELETE_DEMAND: "DELETE_DEMAND",
  MANAGE_MERCHANT: "MANAGE_MERCHANT",
  LIST_MERCHANTS: "LIST_MERCHANTS",
  VIEW_MERCHANT: "VIEW_MERCHANT",
  CREATE_MERCHANT: "CREATE_MERCHANT",
  UPDATE_MERCHANT: "UPDATE_MERCHANT",
  DELETE_MERCHANT: "DELETE_MERCHANT",
  MANAGE_GIFT: "MANAGE_GIFT",
  LISTING: "LISTING",
  DELISTING: "DELISTING",
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  MANAGE_QUOTA: "MANAGE_QUOTA",
  ENTRUST: "ENTRUST",
  TRANSFER: "TRANSFER",
  REDEEM_GIFT: "REDEEM_GIFT",
  VIEW_INVENTORY: "VIEW_INVENTORY",
  ISSUE_CERTIFICATE: "ISSUE_CERTIFICATE",
  MANAGE_ORDER: "MANAGE_ORDER",
  CREATE_DURABLE_QRCODE: "CREATE_DURABLE_QRCODE",
  VIEW_ORG_CERTIFICATE_LOGS: "VIEW_ORG_CERTIFICATE_LOGS",
  //MANAGE_SETTLEMENT,
  LIST_SETTLEMENT:"LIST_SETTLEMENT",
  CREATE_SETTLEMENT:"CREATE_SETTLEMENT",
  VIEW_SETTLEMENT:"VIEW_SETTLEMENT",
  SUBMIT_SETTLEMENT:"SUBMIT_SETTLEMENT",
  APPROVE_SETTLEMENT:"APPROVE_SETTLEMENT",
  DELETE_SETTLEMENT:"DELETE_SETTLEMENT",
};
export {
  user, //保存当前登录的user信息
  token, //保存当前登录的token信息
  marketType, //营销活动
  couponType, //票券管理
  listType, //结算中心
  listAddType, //结算添加类型
  Operation, //权限判断,
};
